# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: W Native
email: olucassanchez@gmail.com
description: Engage your audience and monetize your website with premium widgets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wnative.com" # the base hostname & protocol for your site
twitter_username: lucassanchez
github_username:  lucassanchez